Add initial simple integration test

diff --git a/.github/workflows/pb-tests.yml b/.github/workflows/pb-tests.yml
--- a/.github/workflows/pb-tests.yml
+++ b/.github/workflows/pb-tests.yml
@@ -1,6 +1,8 @@
 name: Tests
 "on":
-    pull_request: {}
+    pull_request:
+        branches:
+            - main
     push:
         branches:
             - main
@@ -205,3 +207,34 @@ jobs:
                 richgo test ./...
               env:
                 RICHGO_FORCE_COLOR: "1"
+            - name: Get builders from integration.json
+              id: builders
+              run: |
+                source "${{ github.workspace }}/scripts/.util/builders.sh"
+
+                builders="$(util::builders::list "${{ github.workspace }}/integration.json")"
+                printf "Output: %s\n" "${builders}"
+                printf "::set-output name=builders::%s\n" "${builders}"
+    integration:
+      name: Integration Tests with Builders
+      runs-on: ubuntu-latest
+      needs: unit
+      strategy:
+        matrix:
+          builder: ${{ fromJSON(needs.unit.outputs.builders) }}
+        fail-fast: false  # don't cancel all test jobs when one fails
+      steps:
+      - name: Setup Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.18.x
+
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
+
+      - name: Run Integration Tests
+        run: ./scripts/integration.sh --use-token --builder ${{ matrix.builder }}
+        env:
+          GIT_TOKEN: ${{ github.token }}
